# fly.toml app configuration file generated for comfyui-demo on 2024-06-18T15:13:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = ''
primary_region = 'ord'

[[mounts]]
  source = 'models'
  destination = '/app/models'
  initial_size = '20gb'

[http_service]
  internal_port = 8188
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-8x'
  memory = '16gb'
  gpu_kind = 'l40s'
